"""split_datalist.py — Split data/data.txt into fixed train/val lists.

With only 300 songs, a held-out validation set is the only way to see
overfitting.  The split is song-level (each data.txt line is one unique
song, verified no duplicate json/ogg paths) and SEEDED so it never changes
between runs — commit the two output files so every experiment shares the
same split.

Run from the AudioLab root::

    uv run python script/split_datalist.py                      # 270/30 default
    uv run python script/split_datalist.py --val-count 30 --seed 42

Outputs ``data/train.txt`` and ``data/val.txt`` next to the input list.
"""

from __future__ import annotations

import argparse
import random
import sys
from pathlib import Path


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Split a data list into fixed train/val lists (seeded, song-level)."
    )
    parser.add_argument("--data-list", default="data/data.txt",
                        help="Input list (default: data/data.txt)")
    parser.add_argument("--val-count", type=int, default=30,
                        help="Number of songs held out for validation (default: 30)")
    parser.add_argument("--seed", type=int, default=42,
                        help="Shuffle seed — keep fixed so the split is reproducible")
    parser.add_argument("--force", action="store_true",
                        help="Overwrite existing train.txt/val.txt")
    args = parser.parse_args()

    src = Path(args.data_list)
    if not src.exists():
        print(f"[ERROR] data list not found: {src}", file=sys.stderr)
        sys.exit(1)

    lines = [l for l in src.read_text().splitlines()
             if l.strip() and not l.lstrip().startswith("#")]
    if len(set(lines)) != len(lines):
        print("[ERROR] duplicate lines in data list — fix before splitting",
              file=sys.stderr)
        sys.exit(1)
    if args.val_count <= 0 or args.val_count >= len(lines):
        print(f"[ERROR] --val-count {args.val_count} out of range for "
              f"{len(lines)} entries", file=sys.stderr)
        sys.exit(1)

    train_path = src.parent / "train.txt"
    val_path   = src.parent / "val.txt"
    if (train_path.exists() or val_path.exists()) and not args.force:
        print(f"[ERROR] {train_path} / {val_path} already exist. "
              "The split must stay fixed across runs — pass --force only if "
              "you intend to invalidate all previous experiments.",
              file=sys.stderr)
        sys.exit(1)

    rng = random.Random(args.seed)
    shuffled = lines[:]
    rng.shuffle(shuffled)

    val   = sorted(shuffled[:args.val_count])
    train = sorted(shuffled[args.val_count:])

    header = (f"# generated by script/split_datalist.py "
              f"--seed {args.seed} --val-count {args.val_count} "
              f"from {src.name} ({len(lines)} entries)\n")
    train_path.write_text(header + "\n".join(train) + "\n")
    val_path.write_text(header + "\n".join(val) + "\n")
    print(f"[split] {len(train)} train → {train_path}")
    print(f"[split] {len(val)} val   → {val_path}")


if __name__ == "__main__":
    main()
